-- ============================================================================
-- REAL ESTATE PROPERTY LISTING & MANAGEMENT SYSTEM
-- File: db/schema.sql
-- MVP Baseline Relational Schema (13 Relations in Dependency Order)
-- ============================================================================

-- Drop existing tables in reverse dependency order
DROP TABLE IF EXISTS REVIEW CASCADE;
DROP TABLE IF EXISTS PAYMENT CASCADE;
DROP TABLE IF EXISTS RENTAL_CONTRACT CASCADE;
DROP TABLE IF EXISTS SALE_TRANSACTION CASCADE;
DROP TABLE IF EXISTS TRANSACTION CASCADE;
DROP TABLE IF EXISTS OFFER CASCADE;
DROP TABLE IF EXISTS LISTING CASCADE;
DROP TABLE IF EXISTS OWNERSHIP CASCADE;
DROP TABLE IF EXISTS PROPERTY CASCADE;
DROP TABLE IF EXISTS PROPERTY_TYPE CASCADE;
DROP TABLE IF EXISTS AGENT CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;

-- 1. PERSON
-- Note: Age is derived from DateOfBirth and is NOT stored in normalized schema.
-- PasswordHash is stored for authentication.
CREATE TABLE PERSON (
    PersonID SERIAL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PhoneNo VARCHAR(20),
    DateOfBirth DATE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. CUSTOMER (Subtype of PERSON - 1:1)
CREATE TABLE CUSTOMER (
    CustomerID SERIAL PRIMARY KEY,
    PersonID INT NOT NULL UNIQUE,
    CONSTRAINT fk_customer_person FOREIGN KEY (PersonID) 
        REFERENCES PERSON(PersonID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 3. AGENT (Subtype of PERSON - 1:1)
CREATE TABLE AGENT (
    AgentID SERIAL PRIMARY KEY,
    PersonID INT NOT NULL UNIQUE,
    CONSTRAINT fk_agent_person FOREIGN KEY (PersonID) 
        REFERENCES PERSON(PersonID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 4. PROPERTY_TYPE (Strong Entity / Lookup Catalog)
CREATE TABLE PROPERTY_TYPE (
    PropertyTypeID SERIAL PRIMARY KEY,
    TypeName VARCHAR(50) NOT NULL UNIQUE
);

-- 5. PROPERTY (N:1 with PROPERTY_TYPE)
CREATE TABLE PROPERTY (
    PropertyID SERIAL PRIMARY KEY,
    AreaSqFt NUMERIC(10, 2) NOT NULL,
    Price NUMERIC(14, 2) NOT NULL,
    Description TEXT,
    PropertyTypeID INT NOT NULL,
    CONSTRAINT fk_property_type FOREIGN KEY (PropertyTypeID) 
        REFERENCES PROPERTY_TYPE(PropertyTypeID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 6. OWNERSHIP (N:N junction between CUSTOMER and PROPERTY with composite PK)
CREATE TABLE OWNERSHIP (
    CustomerID INT NOT NULL,
    PropertyID INT NOT NULL,
    OwnershipShare NUMERIC(5, 2) NOT NULL,
    SinceDate DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (CustomerID, PropertyID),
    CONSTRAINT fk_ownership_customer FOREIGN KEY (CustomerID) 
        REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_ownership_property FOREIGN KEY (PropertyID) 
        REFERENCES PROPERTY(PropertyID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 7. LISTING (1:N with PROPERTY, 1:N with AGENT)
CREATE TABLE LISTING (
    ListingID SERIAL PRIMARY KEY,
    PropertyID INT NOT NULL,
    AgentID INT NOT NULL,
    ListPrice NUMERIC(14, 2) NOT NULL,
    ListedDate DATE NOT NULL DEFAULT CURRENT_DATE,
    Status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_listing_property FOREIGN KEY (PropertyID) 
        REFERENCES PROPERTY(PropertyID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_listing_agent FOREIGN KEY (AgentID) 
        REFERENCES AGENT(AgentID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 8. OFFER (1:N with CUSTOMER, N:1 with LISTING)
CREATE TABLE OFFER (
    OfferID SERIAL PRIMARY KEY,
    CustomerID INT NOT NULL,
    ListingID INT NOT NULL,
    OfferAmount NUMERIC(14, 2) NOT NULL,
    OfferDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT fk_offer_customer FOREIGN KEY (CustomerID) 
        REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_offer_listing FOREIGN KEY (ListingID) 
        REFERENCES LISTING(ListingID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 9. TRANSACTION (1:N from LISTING, supertype for SALE and RENTAL)
CREATE TABLE TRANSACTION (
    TransactionID SERIAL PRIMARY KEY,
    ListingID INT NOT NULL,
    TransactionDate DATE NOT NULL DEFAULT CURRENT_DATE,
    TransactionType VARCHAR(20) NOT NULL,
    CONSTRAINT fk_transaction_listing FOREIGN KEY (ListingID) 
        REFERENCES LISTING(ListingID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 10. SALE_TRANSACTION (1:1 ISA Subtype of TRANSACTION)
CREATE TABLE SALE_TRANSACTION (
    TransactionID INT PRIMARY KEY,
    SalePrice NUMERIC(14, 2) NOT NULL,
    RegistrationNo VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT fk_saletransaction_transaction FOREIGN KEY (TransactionID) 
        REFERENCES TRANSACTION(TransactionID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 11. RENTAL_CONTRACT (1:1 ISA Subtype of TRANSACTION)
CREATE TABLE RENTAL_CONTRACT (
    TransactionID INT PRIMARY KEY,
    MonthlyRent NUMERIC(12, 2) NOT NULL,
    LeaseStartDate DATE NOT NULL,
    LeaseEndDate DATE NOT NULL,
    CONSTRAINT fk_rentalcontract_transaction FOREIGN KEY (TransactionID) 
        REFERENCES TRANSACTION(TransactionID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 12. PAYMENT (1:N with TRANSACTION)
CREATE TABLE PAYMENT (
    PaymentID SERIAL PRIMARY KEY,
    TransactionID INT NOT NULL,
    Amount NUMERIC(14, 2) NOT NULL,
    PaymentDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PaymentMode VARCHAR(50) NOT NULL,
    ReferenceNo VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT fk_payment_transaction FOREIGN KEY (TransactionID) 
        REFERENCES TRANSACTION(TransactionID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 13. REVIEW (1:N from CUSTOMER, 1:N from LISTING)
CREATE TABLE REVIEW (
    ReviewID SERIAL PRIMARY KEY,
    CustomerID INT NOT NULL,
    ListingID INT NOT NULL,
    ReviewDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Rating INT NOT NULL,
    Comment TEXT,
    CONSTRAINT fk_review_customer FOREIGN KEY (CustomerID) 
        REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_review_listing FOREIGN KEY (ListingID) 
        REFERENCES LISTING(ListingID) ON DELETE CASCADE ON UPDATE CASCADE
);
